### PR TITLE
Fixed bug

### LINKED ISSUE #5318: Some calculators name under 3D shapes are not visible
## **Describe the bug**

Some calculators name under 3D shapes are not visible

## **Screenshots**

image

### PR DESCRIPTION
**Pull request by abhijeet141**
## Related Issue

- Info about Issue or bug

fix #5318 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

## Screenshots

image

### CODE REVIEW

**Comment by abhijeet141** [comment]
image

@sairish2001 @arpit456jain  I have deleted these lines as it was repeated twice

**Comment by arpit456jain** [comment]
> image
> 
> @sairish2001 @arpit456jain I have deleted these lines as it was repeated twice

@abhijeet141 I think one is for pyramids and one is for bipyramids  am I right @sairish2001 please confirm

**Comment by abhijeet141** [comment]
@arpit456jain Sorry for that it was my mistake i have rectified it

**Comment by arpit456jain** [comment]
yeah now its look good to me :)

**Pull request merged**
