### PR TITLE
Inequalities of triangles fixed

### LINKED ISSUE #3169: Inequalities of triangles
**The answer is not displaying I would like to fix this, Please assign this to me**

b1

### PR DESCRIPTION
**Pull request by madihamallick**
**fix #3169**

### CODE REVIEW

**Comment by abhijeet141** [comment]
@madihamallick I think this calculator is also working fine please check this also once

**Comment by madihamallick** [comment]
> @madihamallick I think this calculator is also working fine please check this also once

No I don't think so. Please check once and let me know ;)

**Comment by abhijeet141** [comment]
> > @madihamallick I think this calculator is also working fine please check this also once
> 
> No I don't think so. Please check once and let me know ;)
> 
> 

Sorry my bad actually for some input it is working fine and the combination which i took it was showing the output 😅

**Comment by madihamallick** [comment]
> > > @madihamallick I think this calculator is also working fine please check this also once
> > 
> > 
> > No I don't think so. Please check once and let me know ;)
> > 
> 
> Sorry my bad actually for some input it is working fine and the combination which i took it was showing the output
> Once take 8 , 12 , 22 as input it is working fine😅

Aye, No worries!

**Pull request merged**
