### PR TITLE
enhanced buttons

### LINKED ISSUE #5225: Some buttons of the calculator are black and not visible!
## Proposal

I would change the button text color.

### PR DESCRIPTION
**Pull request by siddhi-244**
## Related Issue

- some buttons were black and were not visible bcoz of the background

fix #5225 

#### Describe the changes you've made

i have converted the images to text so that the buttons are visible !

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |
Original
Updated

### CODE REVIEW

**Comment by sairish2001** [comment]
for Multiply use × not X 
for Divide use ÷ not /

just copy paste these symbols

**Comment by siddhi-244** [comment]
Sir @sairish2001  I am getting some errors while adding it

**Comment by sairish2001** [comment]
git pull

then 

git push origin main

**Comment by siddhi-244** [comment]
Sir I am doing it from another branch

**Comment by siddhi-244** [comment]
Sir can I open another pull request?

**Comment by siddhi-244** [comment]
@sairish2001  sir what should I do ?

**Comment by siddhi-244** [comment]
Sir plzz can I??

**Comment by sairish2001** [comment]
Okay make another PR

**Comment by sairish2001** [comment]
Actually you are getting this error, due to conflicts,
firstly you need to pull the code from upstream then make a commit to your branch( mistakenly i wrote main)

**Comment by sairish2001** [comment]
if still facing an error, we have a special video in our channel, regarding this

**Comment by siddhi-244** [comment]
@sairish2001 sir I tried it !

**Pull request closed without merging**
