### PR TITLE
Added Steps for heart shape calculator

### LINKED ISSUE #3620: Steps for heart shape calculator
**Please assign this to me**

### PR DESCRIPTION
**Pull request by madihamallick**
**fix #3620**

### CODE REVIEW

**Comment by madihamallick** [comment]
> You are only creating issues for shapes and then you are creating separate issues for adding steps.
> 
> #3619
> Here, you have just provided answer and now you are giving steps for that heart shape calculator.
> Instead you can't do this in a single PR.
> Why to do this separately?
> Just to get points?
> 
> Kindly requesting you not to do this :)

Hey @mehabhalodiya adding a shape calculator is quite a big task so I added shape with calculations in one and the steps in other. what seems spamming here? And I'm not the only one who is doing this...there's a lot of people doing the same recently. Earlier I used to do all in one PR but since others are doing why won't I? And when the project admin or mentors are not having any problem why does this bother you so much. Instead of just spamming on others issue you should start working on some. I guess that would be of some help :)

**Comment by sairish2001** [comment]
@madihamallick Whose steps are complex to add, is fine for creating separate PR for the same, but what if the Addition of steps is only a few lines of task. Most of the participants who created the separate PR, I allowed to do so because for that calculators adding steps is a big task.

**Comment by sairish2001** [comment]
Please make a note, who's steps are just of <5 lines of task, do it into a single PR

**Comment by madihamallick** [comment]
> Please make a note, who's steps are just of <5 approx. lines of task, do it into a single PR

Okay. I will take care of this from now.

**Pull request merged**
