### PR TITLE
Probability calculator added with steps

### LINKED ISSUE #220: Probability calculator
Given a problem it will calculate the probability and will also provide the stepwise solution to the user.

Please assign this to me

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
## Related Issue

Fixes #220 

#### Describe the changes you've made

I have added the probability calculator along with steps.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by Khushi-agarwal** [comment]
@sairish2001 I have resolved the conflicts and also wasn't this issue of level 4?

**Comment by abhijeet141** [comment]
@sairish2001 I think Probability calculator is already present

**Comment by Khushi-agarwal** [comment]
> @sairish2001 I think Probability calculator is already present

This is for the favourable number of events.This is not there.its the empirical probability.

**Comment by abhijeet141** [comment]
> > @sairish2001 I think Probability calculator is already present
> 
> This is for the favourable number of events.This is not there.its the empirical probability which is present.

Okay but as there is a different section of Probability you can just shift your calculator to that section

**Review by sairish2001 — CHANGES_REQUESTED** [review]
Add this option under this Probability Section
@Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
> 
> 
> Add this option under this Probability Section
> @Khushi-agarwal

@sairish2001 done.

**Review by sairish2001 — APPROVED** [review]
Great Work :)

**Pull request merged**
