### PR TITLE
Three Star Calculator added

### LINKED ISSUE #4484: add three star calculator under shapes calculator
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i wud like to add it

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
## Related Issue

Fixes #4484 

#### Describe the changes you've made

I have added the three star calculator along with the steps.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by sairish2001 — APPROVED** [review]
Great Work :)

**Comment by Khushi-agarwal** [comment]
@sairish2001 should I resolve the conflicts?

**Comment by sairish2001** [comment]
> @sairish2001 should I resolve the conflicts?

Yes go ahead :)

**Comment by Khushi-agarwal** [comment]
> > @sairish2001 should I resolve the conflicts?
> 
> Yes go ahead :)

Resolved.

**Pull request merged**
