### PR TITLE
Added trigonometry.html in study section

### LINKED ISSUE #5246: trigoformula.html
Want to add all the basics to advanced trigo formulas and identities.
and this will be under the study section of project.

### PR DESCRIPTION
**Pull request by akash435**
## Related Issue
fixes #5246
## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] My changes generate no new warnings.

### CODE REVIEW

**Comment by sairish2001** [comment]
You need to link this page to index.html

**Comment by sairish2001** [comment]
It's not a difficult task, just under Calculus section add a list/option of it. and in loadcalculator function pass a filename.

you can check other options, for more clarity

**Comment by akash435** [comment]
In calculus section or trigonometry section below it?

**Comment by sairish2001** [comment]
Oh sorry! under Trigonometry

**Comment by akash435** [comment]
@sairish2001 , i have linked with index.html, please check it

**Comment by akash435** [comment]
In index.html it looks like this named Trigonometry Basics,

**Review by sairish2001 — APPROVED** [review]

**Pull request merged**
