### PR TITLE
Speed Distance Time calculator improvised.

### PR DESCRIPTION
**Pull request by jugeshraghav**
## Related Issue

- Info about Issue or bug

fix #[issue number that will be closed through this PR]

#5304 

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by jugeshraghav** [comment]
please have a look and suggest me changes if any. @arpit456jain @sairish2001

**Comment by arpit456jain** [comment]
@jugeshraghav kindly try to share some screen shots or video  so that mentors or PA's can review the PR easily  :)

**Comment by arpit456jain** [comment]
in my system its not working in fact speed calculator is not opening all the other things are working 
can you please confirm this @jugeshraghav

**Comment by jugeshraghav** [comment]
I have resolved the errors. Please check it now.

**Comment by arpit456jain** [comment]
Looks good to me . Great work @jugeshraghav

**Comment by jugeshraghav** [comment]
Thank you so much😇

**Review by sairish2001 — CHANGES_REQUESTED** [review]
Great work :)
Few changes needs to be made
1. Define functions in library/logicjavascript.js file, see solveFraction() function for reference, here we are passing values as parameters and returning a object, you need to follow same method for these two functions.

2. now just call these functions in the `speedDistanceTimeCalculator.html` file as we did in `solveFraction.html` file

Why these changes required?
As we are planning to release it as a library, so that anyone can use these predefined functions, by just calling them

**Comment by jugeshraghav** [comment]
Sure, will do that.

**Review by sairish2001 — APPROVED** [review]

**Review by sairish2001 — APPROVED** [review]
Great Work :)

**Comment by jugeshraghav** [comment]
Thank you so much.

**Pull request merged**
