### PR TITLE
Added options in graphandshapes.html

### LINKED ISSUE #5340: Add options in graphShapes.html
## **Is your feature request related to a problem? Please describe.**
I would like to add options in graphShapes.html
Please assign me this issue.

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
## Related Issue

- Info about Issue or bug

Fixes #5340 

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Khushi-agarwal any ss or something ??

**Comment by Khushi-agarwal** [comment]
image

**Comment by Khushi-agarwal** [comment]
I have referred to the linearAlgebra.html page as said by @sairish2001 .

**Comment by sairish2001** [comment]
> image
> 

This happens because you directly Opened this page, try to open from index.html, by running live server

**Comment by Khushi-agarwal** [comment]
> > image
> 
> This happens because you directly Opened this page, try to open from index.html, by running live server

Do I have to make any changes?

**Review by sairish2001 — APPROVED** [review]

**Pull request merged**
