### PR TITLE
Faulhaber Formula

### PR DESCRIPTION
**Pull request by deepaahuja92**
## Related Issue

- Info about Issue or bug

fix #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x]My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
-  [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by sairish2001** [comment]
Don't make different PR's for different sections. Make a single PR at the end

**Comment by sairish2001** [comment]
Can you please tell, are you done with this issue?

**Comment by deepaahuja92** [comment]
No..actually there were  many deletions and insertions  and also the many
files so I thought to push it first and then I will work upon the rest
tomorrow as there are many calculators to update.Can I make 1 commit daily
as making only the 1 commit in such a issue at the end will be very large.

**Comment by sairish2001** [comment]
No problem, what makes you comfortable do it.
But can you please tell how many sections are done by you till now?

**Comment by deepaahuja92** [comment]
I have done 9 sections till now.But tomorrow I will do more.

**Comment by sairish2001** [comment]
Okay great! 
once you done with all do tell me

**Comment by deepaahuja92** [comment]
okay sir

**Comment by sairish2001** [comment]
as I am seeing, your branch is not updated, Kindly fetch from upstream and then continue your work

**Comment by deepaahuja92** [comment]
sir but what all the changes I have made now,they will be gone if I will
update the branch.Can I commit it before and then update?

**Comment by sairish2001** [comment]
I have merged this PR and resolved the conflicts, Kindly update your branch and continue your work, otherwise again conflicts will occur

**Pull request merged**
