### PR TITLE
Incirle of Triangle Calculator

### LINKED ISSUE #5129: Incircle of a triangle Calculator
**Please assign this to me**

### PR DESCRIPTION
**Pull request by AnkitaKataria22**
fix #5129 

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by AnkitaKataria22** [comment]
image

**Review by sairish2001 — CHANGES_REQUESTED** [review]
This repository is based on HTML,CSS, JavaScript. So you need to create UI and define function in logicjavaScript.js file as a library function and call in the file you will create.

**Comment by arpit456jain** [comment]
@AnkitaKataria22 any updates ? if you need any kind of help then feel free to ask but try to do the task within given deadline :)

**Comment by arpit456jain** [comment]
@AnkitaKataria22

**Pull request closed without merging**
