### PR TITLE
count of nested polygons drawn by joining vertices

### LINKED ISSUE #2896: count of nested polygons drawn by joining vertices
**The answer is not displaying. I would like to fix this please assign this to me**

b2

### PR DESCRIPTION
**Pull request by madihamallick**
**fix #2896**

### CODE REVIEW

**Comment by khareyash05** [comment]
@madihamallick May I know what specific changes have you made in the same? As i Had already made and you have just changed variable names.. Also for the steps I had made an issue before #2636

**Comment by khareyash05** [comment]
@sairish2001 KIndly look into this

**Comment by sairish2001** [comment]
@madihamallick Please don't spam🙏

**Comment by khareyash05** [comment]
@sairish2001 thank you....

**Pull request merged**
