### PR TITLE
Steps for Decimal to BCD

### LINKED ISSUE #1658: Add working steps for decimal / bcd code converter
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

### PR DESCRIPTION
**Pull request by Amit366**
## Related Issue

- Info about Issue or bug

fix #1658 

#### Describe the changes you've made

ASteps for Decimal to BCD

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Amit366** [comment]
@sairish2001 please review

**Comment by AB-san** [comment]
@Amit366  you have made changes for addition of bcd numbers , but the issue is about adding working steps for bcd to decimal converter

**Comment by Amit366** [comment]
I didn't find it. I found only this one in the logic. Js file

**Comment by AB-san** [comment]
> Please tell me the line from which the conversion is.

17729 to 17747

**Comment by Amit366** [comment]
@sairish2001 please review

**Pull request merged**
