### PR TITLE
Modified Hyperfind funtion into Library function 

### PR DESCRIPTION
**Pull request by jasminekaur-prog**
#5352 

Converted Hyperfind Function into Library Function 

fix #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by jasminekaur-prog** [comment]
@sairish2001 Please review this

**Comment by arpit456jain** [comment]
@jasminekaur-prog please check this PR since there is no change in this PR

**Comment by jasminekaur-prog** [comment]
@arpit456jain Yes I think there has been some mistake...I checked it..Should I close this pull request and do it again ?

**Comment by arpit456jain** [comment]
Yes @jasminekaur-prog

**Comment by arpit456jain** [comment]
@jasminekaur-prog make a new branch and make PR from that branch not from the main if you are facing any problem then let me know

**Pull request closed without merging**
