### PR TITLE
Steps added for binomial distribution pmf

### LINKED ISSUE #3372: steps to Binomial Distribution PMF Calculator
**Please assign this to me**

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
## Related Issue

Fixes #3372 

fix #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
I have added the steps.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by sairish2001 — COMMENTED** [review]
Actually you created a Calculator only, and haven't added steps for it, i.e. how it is working / how it's calculating. 
Can you add steps? if not comfortable with it do tell us

**Comment by Khushi-agarwal** [comment]
> Actually you created a Calculator only, and haven't added steps for it, i.e. how it is working / how it's calculating.
> Can you add steps? if not comfortable with it do tell us

@sairish2001 Yes I will add steps.

**Comment by sairish2001** [comment]
have a look to
`calculators/solveFraction.html`
and 
`library/logicjavascript.js` -> `function solveFraction(num1,num2)` 

be make sure you use same thing, as did in these. because we are planning to release it as a library also, so your function should follow these rules.

1. make separate file in Calculators folder
2. link with index.html by just calling `loadcalculator('filename')` in the navbar.
3. put the required function in the `library/logicjavascript.js`

**Comment by Khushi-agarwal** [comment]
> have a look to
> `calculators/solveFraction.html`
> and
> `library/logicjavascript.js` -> `function solveFraction(num1,num2)`
> 
> be make sure you use same thing, as did in these. because we are planning to release it as a library also, so your function should follow these rules.
> 
> 1. make separate file in Calculators folder ( camelCase for filename )
> 2. link with index.html by just calling `loadcalculator('filename')` in the navbar.
> 3. put the required function in the `library/logicjavascript.js`
> 
> @Khushi-agarwal

@sairish2001 Can you please help me by telling me how to link the calculator file with index.html.

**Comment by sairish2001** [comment]
just call loadcalculator ('filename');
instead of calling on workink.js

**Comment by sairish2001** [comment]
Change file name from pmf.html to `binomialDistributionPmf.html`

**Comment by Khushi-agarwal** [comment]
> Change file name from pmf.html to `binomialDistributionPmf.html`

Done.Kindly review it. @sairish2001

**Review by sairish2001 — APPROVED** [review]
Great Work :)
Appreciated your patience

**Pull request merged**
