### PR TITLE
Janhvi11

### LINKED ISSUE #5239: Change the home page look
Want to make the home page more creative like by adding background etc.

### PR DESCRIPTION
**Pull request by tjanhvi**
## Related Issue

- Info about Issue or bug

fix #5239

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots
image

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by sairish2001** [comment]
Can you please share some screenshots?

**Comment by arpit456jain** [comment]
@tjanhvi please share a video recoding also because i think there is some problem its looking like this.

https://user-images.githubusercontent.com/55352601/121896495-fb236780-cd3e-11eb-8794-508662a4626c.mp4

@sairish2001 can you please confirm whether its happening at your side also or not .

**Comment by tjanhvi** [comment]
> @tjanhvi please share a video recoding also because i think there is some problem its looking like this.
> 
>  2021-06-14.18-28-44.mp4 
> @sairish2001 can you please confirm whether its happening at your side also or not .

okay :)

**Comment by sairish2001** [comment]
@tjanhvi 
if you are facing problem while recording video, you can just put 2-3 screenshots

**Comment by tjanhvi** [comment]
> @tjanhvi please share a video recoding also because i think there is some problem its looking like this.
> 
>  2021-06-14.18-28-44.mp4 
> @sairish2001 can you please confirm whether its happening at your side also or not .

image
No sir, this is not happening from my side.

**Comment by tjanhvi** [comment]
> @tjanhvi please share a video recoding also because i think there is some problem its looking like this.
> 
>  2021-06-14.18-28-44.mp4 
> @sairish2001 can you please confirm whether its happening at your side also or not .
vedio
No this is not happening from my side.

**Comment by sairish2001** [comment]
Really Great Work! after a lot of issues regarding designing the background image, this is the satisfactory one. The image looks too great.

**Comment by tjanhvi** [comment]
> Really Great Work! after a lot of issues regarding designing the background image, this is the satisfactory one. The image looks too great.

Thanks a lot :)

**Pull request merged**
