### PR TITLE
Added awesome background in the homepage

### LINKED ISSUE #5239: Change the home page look
Want to make the home page more creative like by adding background etc.

### PR DESCRIPTION
**Pull request by tjanhvi**
## Related Issue

- Info about Issue or bug

fix #5239

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots
image

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by sairish2001** [comment]
@tjanhvi Can you please share the screenshot.
And can you please tell have you created this by yourself or downloaded from elsewhere because we don't want any plagiarized content

**Comment by tjanhvi** [comment]
> @tjanhvi Can you please share the screenshot.
> And can you please tell have you created this by yourself or downloaded from elsewhere because we don't want any plagiarized content

downloaded from the website and adjust the background image in the css by using the css background features.
Can you please let me know how to do this by css. Any guidelines please..

**Comment by arpit456jain** [comment]
@tjanhvi you can make your own image by using [canva](https://www.canva.com/en_in/) . just have to drag and drop content .
Its very easy to use and you can make some great designs of your own

**Comment by tjanhvi** [comment]
> @tjanhvi you can make your own design by using [canva](https://www.canva.com/en_in/) . just have to drag and drop content .
> Its very easy to use and you can make some great designs of your own

sure , I will do that

**Pull request closed without merging**
