### PR TITLE
add examples for calculators- juggler,padovan,recamann,collatz, SOS 1/1 +(1+2)/(1*2)

### LINKED ISSUE #4528: add example button for calculators- juggler,padovan,recamann,collatz, SOS 1/1 +(1+2)/(1*2)
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

i wud like to add it

### PR DESCRIPTION
**Pull request by AB-san**
## Related Issue

- Info about Issue or bug

fix #4528 

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by AB-san** [comment]
@sairish2001 can you please resolve th ecommits as i dont have acces to do tht

**Comment by AB-san** [comment]
@sairish2001  i dont hv the write access to resolve the conflicts can you resolve the conflicts

**Comment by sairish2001** [comment]
I tried many times, still won't able to merge

**Comment by AB-san** [comment]
> I tried many times, still won't able to merge

is it possible to give me the write accesss so tht i can ?

**Comment by sairish2001** [comment]
> > I tried many times, still won't able to merge
> 
> is it possible to give me the write accesss so tht i can ?

Send me few screenshots, so that I can configure what's the problem

**Comment by AB-san** [comment]
> > > I tried many times, still won't able to merge
> > 
> > 
> > is it possible to give me the write accesss so tht i can ?
> 
> Send me few screenshots, so that I can configure what's the problem

@sairish2001  okay

**Comment by AB-san** [comment]
image
no option for me to resolve it

**Comment by AB-san** [comment]
changes that i made in  logicjs file for this pr - 

image

image

image

**Comment by AB-san** [comment]
> changes that i made in logicjs file for this pr -
> 
> image
> 
> image
> 
> image

@sairish2001 if possible make those chngs and then merge

**Comment by AB-san** [comment]
@sairish2001  shhud i make a new pr ??

**Comment by sairish2001** [comment]
> @sairish2001  shhud i make a new pr ??

Yes, please

**Comment by AB-san** [comment]
@sairish2001 I have no idea but for some reason , each n evrey changes that i made in this pr are there in the main file and it was added by u only with a commit name - "resolved"

Anyways this pr is having merge conflicts because of a bug which i hv solved in pr#

**Pull request closed without merging**
