### PR TITLE
Added Particles.js in background

### LINKED ISSUE #5300: I would like to add particle.js in the background
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

### PR DESCRIPTION
**Pull request by abhijeet141**
## Related Issue

- Info about Issue or bug

fix #5300 
#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

image

### CODE REVIEW

**Comment by abhijeet141** [comment]
@sairish2001 kindly review the changes

**Review by sairish2001 — APPROVED** [review]
Looks Awesome :)
Great Work

**Comment by abhijeet141** [comment]
@sairish2001 I have added in newdesign.html pages if this looks fine to you then should i add it in index.html page ?

**Comment by sairish2001** [comment]
No need, soon we will shift this into index.html, as soon as all the sections will Organized

**Comment by abhijeet141** [comment]
> No need, soon we will shift this into index.html, as soon as all the sections will Organized

Okay :)

**Comment by abhijeet141** [comment]
https://user-images.githubusercontent.com/67696867/123470375-f0f04b80-d611-11eb-8517-ef7a82bc260d.mp4

@sairish2001 Have a look at this particles design

**Comment by sairish2001** [comment]
> 
> https://user-images.githubusercontent.com/67696867/123470375-f0f04b80-d611-11eb-8517-ef7a82bc260d.mp4
> 
> @sairish2001 Have a look at this particles design

No this, not looks that much good

**Comment by abhijeet141** [comment]
> > record_000004.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > @sairish2001 Have a look at this particles design
> 
> No this, not looks that much good

Okay

**Pull request merged**
