### PR TITLE
speed calculator is created.

### PR DESCRIPTION
**Pull request by jugeshraghav**
## Related Issue

#5254 

fix #[issue number that will be closed through this PR]

#### Describe the changes you've made

I have created the speed calculator if distance and time of an object is given.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by jugeshraghav** [comment]
please review it and guide me for further changes. @sairish2001 @arpit456jain

**Review by sairish2001 — CHANGES_REQUESTED** [review]
You need to add option for it, also under General Maths section.

**Comment by jugeshraghav** [comment]
Please explain it, I didn't get exactly what do.

**Comment by jugeshraghav** [comment]
I am not able to find the general maths section

**Comment by arpit456jain** [comment]
image

after trigonometry section  @jugeshraghav

**Comment by jugeshraghav** [comment]
In the code 😓

**Comment by jugeshraghav** [comment]
I have added the calculator in the general maths section . Please review the changes. @sairish2001  @arpit456jain

**Comment by arpit456jain** [comment]
ok great @jugeshraghav we will merge your PR soon :)

**Comment by jugeshraghav** [comment]
Thank you so much😇

**Comment by jugeshraghav** [comment]
..

**Pull request merged**
