### PR TITLE
Large-cal

### PR DESCRIPTION
**Pull request by surbhi594**
Tried to resolve the issue. 
 Please review it.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@surbhi594 try to resolve these merge conflicts and kindly share some screenshots

**Comment by arpit456jain** [comment]
@surbhi594 kindly mention the issue which you are solving

**Comment by sairish2001** [comment]
I think you commited some old changes,
Kindly Update your branch

**Comment by sairish2001** [comment]
Like in index.html we don't have this Toggle type button. There's something which you commited which is not updated. Have a look

**Comment by surbhi594** [comment]
ok, I will look into it.

**Comment by sairish2001** [comment]
@surbhi594 Kindly look into it

**Review by sairish2001 — APPROVED** [review]

**Pull request merged**
